/**
 * Catálogo central de permisos utilizados por Server Actions.
 *
 * Evita strings repetidos y errores tipográficos.
 */
export const PERMISOS = {
    // Inicio
    INICIO_VER: "INICIO_VER",

    // Agenda
    AGENDA_VER: "AGENDA_VER",
    AGENDA_CREAR: "AGENDA_CREAR",
    AGENDA_EDITAR: "AGENDA_EDITAR",
    AGENDA_CONFIRMAR: "AGENDA_CONFIRMAR",
    AGENDA_EN_ESPERA: "AGENDA_EN_ESPERA",
    AGENDA_INICIAR: "AGENDA_INICIAR",
    AGENDA_FINALIZAR: "AGENDA_FINALIZAR",
    AGENDA_REPROGRAMAR: "AGENDA_REPROGRAMAR",
    AGENDA_CANCELAR: "AGENDA_CANCELAR",
    AGENDA_NO_ASISTIO: "AGENDA_NO_ASISTIO",
    AGENDA_COBRAR: "AGENDA_COBRAR",

    // Clientes
    CLIENTES_VER: "CLIENTES_VER",
    CLIENTES_CREAR: "CLIENTES_CREAR",
    CLIENTES_EDITAR: "CLIENTES_EDITAR",
    CLIENTES_FICHA_BELLEZA: "CLIENTES_FICHA_BELLEZA",
    CLIENTES_FORMULAS: "CLIENTES_FORMULAS",
    CLIENTES_NOTAS: "CLIENTES_NOTAS",
    CLIENTES_ARCHIVOS: "CLIENTES_ARCHIVOS",

    // Trabajadores
    TRABAJADORES_VER: "TRABAJADORES_VER",
    TRABAJADORES_CREAR: "TRABAJADORES_CREAR",
    TRABAJADORES_EDITAR: "TRABAJADORES_EDITAR",
    TRABAJADORES_HORARIOS: "TRABAJADORES_HORARIOS",
    TRABAJADORES_AUSENCIAS: "TRABAJADORES_AUSENCIAS",
    TRABAJADORES_PAGO: "TRABAJADORES_PAGO",

    // Servicios
    SERVICIOS_VER: "SERVICIOS_VER",
    SERVICIOS_CREAR: "SERVICIOS_CREAR",
    SERVICIOS_EDITAR: "SERVICIOS_EDITAR",
    SERVICIOS_TRABAJADORES: "SERVICIOS_TRABAJADORES",
    SERVICIOS_MATERIALES: "SERVICIOS_MATERIALES",
    SERVICIOS_COMISIONES: "SERVICIOS_COMISIONES",

    // Caja
    CAJA_VER: "CAJA_VER",
    CAJA_ABRIR: "CAJA_ABRIR",
    CAJA_COBRAR: "CAJA_COBRAR",
    CAJA_VENTA_DIRECTA: "CAJA_VENTA_DIRECTA",
    CAJA_INGRESO_MANUAL: "CAJA_INGRESO_MANUAL",
    CAJA_EGRESO_MANUAL: "CAJA_EGRESO_MANUAL",
    CAJA_CERRAR: "CAJA_CERRAR",
    CAJA_VER_CIERRES: "CAJA_VER_CIERRES",
    CAJA_ANULAR_VENTA: "CAJA_ANULAR_VENTA",

    // Cuentas por cobrar
    CUENTAS_COBRAR_VER: "CUENTAS_COBRAR_VER",
    CUENTAS_COBRAR_ABONAR: "CUENTAS_COBRAR_ABONAR",
    CUENTAS_COBRAR_EDITAR: "CUENTAS_COBRAR_EDITAR",

    // Inventario
    INVENTARIO_VER: "INVENTARIO_VER",
    INVENTARIO_PRODUCTOS_CREAR: "INVENTARIO_PRODUCTOS_CREAR",
    INVENTARIO_PRODUCTOS_EDITAR: "INVENTARIO_PRODUCTOS_EDITAR",
    INVENTARIO_AJUSTAR: "INVENTARIO_AJUSTAR",
    INVENTARIO_TRASLADAR: "INVENTARIO_TRASLADAR",
    INVENTARIO_VER_MOVIMIENTOS: "INVENTARIO_VER_MOVIMIENTOS",

    // Compras
    PROVEEDORES_VER: "PROVEEDORES_VER",
    PROVEEDORES_CREAR: "PROVEEDORES_CREAR",
    PROVEEDORES_EDITAR: "PROVEEDORES_EDITAR",
    COMPRAS_VER: "COMPRAS_VER",
    COMPRAS_CREAR: "COMPRAS_CREAR",
    COMPRAS_PAGAR: "COMPRAS_PAGAR",
    COMPRAS_ANULAR: "COMPRAS_ANULAR",

    // Finanzas
    FINANZAS_VER: "FINANZAS_VER",
    FINANZAS_INGRESO: "FINANZAS_INGRESO",
    FINANZAS_GASTO: "FINANZAS_GASTO",
    FINANZAS_HISTORIAL: "FINANZAS_HISTORIAL",
    FINANZAS_RESUMEN: "FINANZAS_RESUMEN",
    FINANZAS_CATEGORIAS: "FINANZAS_CATEGORIAS",
    FINANZAS_EXPORTAR: "FINANZAS_EXPORTAR",

    // Reportes
    REPORTES_VER: "REPORTES_VER",
    REPORTES_VENTAS: "REPORTES_VENTAS",
    REPORTES_CITAS: "REPORTES_CITAS",
    REPORTES_CLIENTES: "REPORTES_CLIENTES",
    REPORTES_INVENTARIO: "REPORTES_INVENTARIO",
    REPORTES_COMPRAS: "REPORTES_COMPRAS",
    REPORTES_FINANCIEROS: "REPORTES_FINANCIEROS",
    REPORTES_EXPORTAR: "REPORTES_EXPORTAR",

    // Notificaciones
    NOTIFICACIONES_VER: "NOTIFICACIONES_VER",
    NOTIFICACIONES_GESTIONAR: "NOTIFICACIONES_GESTIONAR",
    NOTIFICACIONES_CONFIGURAR: "NOTIFICACIONES_CONFIGURAR",

    // Configuracion
    CONFIGURACION_VER: "CONFIGURACION_VER",
    CONFIGURACION_EDITAR: "CONFIGURACION_EDITAR",
    CONFIGURACION_POS: "CONFIGURACION_POS",

    // Usuarios
    USUARIOS_VER: "USUARIOS_VER",
    USUARIOS_CREAR: "USUARIOS_CREAR",
    USUARIOS_EDITAR: "USUARIOS_EDITAR",
    USUARIOS_CAMBIAR_ESTADO: "USUARIOS_CAMBIAR_ESTADO",
    USUARIOS_PERMISOS: "USUARIOS_PERMISOS",
    USUARIOS_ROLES: "USUARIOS_ROLES",
} as const;

export type CodigoPermiso =
    (typeof PERMISOS)[keyof typeof PERMISOS];
